"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 13:15:10.092916
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('catalog_entries',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('audience', sa.Text(), nullable=False),
    sa.Column('niche', sa.String(length=240), nullable=False),
    sa.Column('style', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(length=240), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('duration_max', sa.Integer(), nullable=False),
    sa.Column('words_per_minute', sa.Integer(), nullable=True),
    sa.Column('scene_seconds', sa.Float(), nullable=False),
    sa.Column('visual_style', sa.Text(), nullable=False),
    sa.Column('default_quality', sa.String(length=16), nullable=False),
    sa.Column('tts_model', sa.String(length=160), nullable=True),
    sa.Column('tts_voice', sa.String(length=160), nullable=True),
    sa.Column('tts_speed', sa.Float(), nullable=False),
    sa.Column('tts_style', sa.Text(), nullable=False),
    sa.Column('thumbnail_style', sa.Text(), nullable=False),
    sa.Column('thumbnail_text_mode', sa.String(length=16), nullable=False),
    sa.Column('auto_learn', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('lane', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('scene_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_group', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('message', sa.String(length=400), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('worker_id', sa.String(length=80), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('run_after', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index('ix_jobs_claim', ['status', 'priority', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_scene_id'), ['scene_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('usage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('scene_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('operation', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=160), nullable=False),
    sa.Column('generation_id', sa.String(length=120), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('reasoning_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('cost_source', sa.String(length=16), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_records_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_generation_id'), ['generation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_project_id'), ['project_id'], unique=False)

    op.create_table('worker_heartbeats',
    sa.Column('worker_id', sa.String(length=80), nullable=False),
    sa.Column('hostname', sa.String(length=120), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('seen_at', sa.DateTime(), nullable=False),
    sa.Column('info', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('quality', sa.String(length=16), nullable=False),
    sa.Column('script', sa.Text(), nullable=False),
    sa.Column('script_updated_at', sa.DateTime(), nullable=True),
    sa.Column('analysis', sa.JSON(), nullable=True),
    sa.Column('analysis_at', sa.DateTime(), nullable=True),
    sa.Column('analysis_script_hash', sa.String(length=64), nullable=False),
    sa.Column('scenes_planned_at', sa.DateTime(), nullable=True),
    sa.Column('scenes_script_hash', sa.String(length=64), nullable=False),
    sa.Column('target_minutes', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('metadata_suggestions', sa.JSON(), nullable=True),
    sa.Column('selected_title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_channel_id'), ['channel_id'], unique=False)

    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note', sa.String(length=400), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'version')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_channel_id'), ['channel_id'], unique=False)

    op.create_table('feedback_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('scene_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_events_channel_id'), ['channel_id'], unique=False)

    op.create_table('scenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('narration', sa.Text(), nullable=False),
    sa.Column('est_duration', sa.Float(), nullable=False),
    sa.Column('audio_duration', sa.Float(), nullable=True),
    sa.Column('visual_description', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('asset_type', sa.String(length=16), nullable=False),
    sa.Column('ai_asset_type', sa.String(length=16), nullable=False),
    sa.Column('asset_type_reason', sa.Text(), nullable=False),
    sa.Column('motion', sa.String(length=16), nullable=False),
    sa.Column('sentence_start', sa.Integer(), nullable=True),
    sa.Column('sentence_end', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('image_asset_id', sa.Integer(), nullable=True),
    sa.Column('clip_asset_id', sa.Integer(), nullable=True),
    sa.Column('audio_asset_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.create_index('ix_scenes_project_position', ['project_id', 'position'], unique=False)

    op.create_table('skill_learnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skill_learnings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_learnings_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_learnings_status'), ['status'], unique=False)

    op.create_table('thumbnail_concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('idea', sa.Text(), nullable=False),
    sa.Column('emotion', sa.String(length=200), nullable=False),
    sa.Column('composition', sa.Text(), nullable=False),
    sa.Column('overlay_text', sa.String(length=120), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('selected_asset_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('thumbnail_concepts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thumbnail_concepts_project_id'), ['project_id'], unique=False)

    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=True),
    sa.Column('concept_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('path', sa.String(length=600), nullable=False),
    sa.Column('mime', sa.String(length=80), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=160), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('generation_id', sa.String(length=120), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['thumbnail_concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_scene_id'), ['scene_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_scene_id'))
        batch_op.drop_index(batch_op.f('ix_assets_project_id'))
        batch_op.drop_index(batch_op.f('ix_assets_concept_id'))

    op.drop_table('assets')
    with op.batch_alter_table('thumbnail_concepts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thumbnail_concepts_project_id'))

    op.drop_table('thumbnail_concepts')
    with op.batch_alter_table('skill_learnings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_learnings_status'))
        batch_op.drop_index(batch_op.f('ix_skill_learnings_channel_id'))

    op.drop_table('skill_learnings')
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.drop_index('ix_scenes_project_position')

    op.drop_table('scenes')
    with op.batch_alter_table('feedback_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_events_channel_id'))

    op.drop_table('feedback_events')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_channel_id'))

    op.drop_table('skills')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_channel_id'))

    op.drop_table('projects')
    op.drop_table('worker_heartbeats')
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_records_project_id'))
        batch_op.drop_index(batch_op.f('ix_usage_records_job_id'))
        batch_op.drop_index(batch_op.f('ix_usage_records_generation_id'))
        batch_op.drop_index(batch_op.f('ix_usage_records_created_at'))
        batch_op.drop_index(batch_op.f('ix_usage_records_channel_id'))

    op.drop_table('usage_records')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_scene_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_project_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_parent_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_created_at'))
        batch_op.drop_index('ix_jobs_claim')
        batch_op.drop_index(batch_op.f('ix_jobs_channel_id'))

    op.drop_table('jobs')
    op.drop_table('channels')
    op.drop_table('catalog_entries')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
